import { IAuditorium, AuditoriumEnum } from '../models/IAuditorim';
import { SubjectEnum } from './subjects';

export const auditoriums : IAuditorium [] = [
    {
        AuditoriumId : 1,
        Name : AuditoriumEnum.Regular , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.GameDesign,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.Math,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
    {
        AuditoriumId : 2,
        Name : AuditoriumEnum.Small , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
    {
        AuditoriumId : 3,
        Name : AuditoriumEnum.Big60 , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    }, 
    {
        AuditoriumId : 4,
        Name :AuditoriumEnum.Big300 , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.Math,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
    {
        AuditoriumId : 5,
        Name : AuditoriumEnum.Computer15 , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.GameDesign,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
        ]
    }, 
    {
        AuditoriumId : 6,
        Name : AuditoriumEnum.Computer20 , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.GameDesign,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
        ]
    }, 
    {
        AuditoriumId : 7,
        Name : AuditoriumEnum.Drawing , 
        AuditoriumTypeId : 1 ,
        Subjects : [
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.GameDesign,
        ]
    }, 
    {
        AuditoriumId : 8,
        Name : AuditoriumEnum.MediaComputers , 
        AuditoriumTypeId : 1 ,
        Subjects : [
            SubjectEnum.MediaEducationAndTheMarketplace,
        ]
    }, 
    {
        AuditoriumId : 9,
        Name : AuditoriumEnum.MediaAuditorium , 
        AuditoriumTypeId : 1 ,
        Subjects : [
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.GameDesign,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.MediaEducationAndTheMarketplace,
        ]
    }, 
    {
        AuditoriumId : 10,
        Name : AuditoriumEnum.LawAuditorium , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.Georgian,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.SeminarInHistoricalMethods,
        ]
    },
    {
        AuditoriumId : 11,
        Name : AuditoriumEnum.Regular , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.GameDesign,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.Math,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
    {
        AuditoriumId : 12,
        Name : AuditoriumEnum.Regular , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.GameDesign,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.Math,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
    {
        AuditoriumId : 13,
        Name : AuditoriumEnum.Regular , 
        AuditoriumTypeId : 1,
        Subjects : [
            SubjectEnum.AdvancedDataStructures,
            SubjectEnum.ArchitectureStudio,
            SubjectEnum.BiologicalChemistry,
            SubjectEnum.DarwinAndDesign,
            SubjectEnum.English,
            SubjectEnum.FinanceTheory,
            SubjectEnum.FundamentalsOfBiology,
            SubjectEnum.GameDesign,
            SubjectEnum.Georgian,
            SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
            SubjectEnum.HighlightsOfCalculus,
            SubjectEnum.InterrogativeDesign,
            SubjectEnum.IntroductionToBioengineering,
            SubjectEnum.IntroductionToBiology,
            SubjectEnum.IntroductionToModelingAndSimulation,
            SubjectEnum.IntroductionToPsychology,
            SubjectEnum.IntroductoryQuantumMechanics,
            SubjectEnum.LinearAlgebra,
            SubjectEnum.Math,
            SubjectEnum.MediaEducationAndTheMarketplace,
            SubjectEnum.MulticoreProgramming,
            SubjectEnum.NonlinearProgramming,
            SubjectEnum.PrinciplesOfMicroeconomics,
            SubjectEnum.QuantumPhysicsI,
            SubjectEnum.QuantumPhysicsII,
            SubjectEnum.SeminarInHistoricalMethods,
            SubjectEnum.SystemsBiology
        ]
    },
]


