import { ILecturer } from '../models/ILecturer';
import { LecturerEnum } from '../models/ILecturerType';
import { SubjectEnum } from './subjects';

export const lecturers : ILecturer [] = [{
    Id : 1 ,
    PersonalId : '1111111111',
    FirstName : 'Nika',
    LastName : 'Giorgadze',
    PhoneNumber : '555675678987',
    HomeNumber : '',
    Address : 'Tbilisi',
    Email : 'Nika@Sessions.com',
    LecturerType : LecturerEnum.Permanent,
    Subjects : [
        SubjectEnum.MediaEducationAndTheMarketplace
    ],
}, {
    Id : 2 ,
    PersonalId : '2222222222222',
    FirstName : 'Giorgi',
    LastName : 'Balakhadze',
    PhoneNumber : '555675678987',
    HomeNumber : '',
    Address : 'Tbilisi',
    Email : 'Giorgi@Sessions.com',
    LecturerType : LecturerEnum.Permanent,
    Subjects : [
        SubjectEnum.Math
    ],
}, {
    Id : 3 ,
    PersonalId : '333333333',
    FirstName : 'Mariam',
    LastName : 'Giorgadze',
    PhoneNumber : '555675678987',
    HomeNumber : '',
    Address : 'Tbilisi',
    Email : 'MAriam@Sessions.com',
    LecturerType : LecturerEnum.Permanent,
    Subjects : [
        SubjectEnum.AdvancedDataStructures,
        SubjectEnum.ArchitectureStudio,
        SubjectEnum.BiologicalChemistry,
        SubjectEnum.DarwinAndDesign,
        SubjectEnum.English,
        SubjectEnum.FundamentalsOfBiology,
        SubjectEnum.GameDesign,
        SubjectEnum.Georgian,
        SubjectEnum.GraphTheoryAndAdditiveCombinatorics,
        SubjectEnum.HighlightsOfCalculus,
        SubjectEnum.InterrogativeDesign,
        SubjectEnum.IntroductionToBioengineering,
        SubjectEnum.IntroductionToBiology,
        SubjectEnum.IntroductionToModelingAndSimulation,
        SubjectEnum.IntroductionToPsychology,
        SubjectEnum.IntroductoryQuantumMechanics,
        SubjectEnum.LinearAlgebra,

    ],
},
{
    Id : 4 ,
    PersonalId : '444444444',
    FirstName : 'Nino',
    LastName : 'Giorgadze',
    PhoneNumber : '555675678987',
    HomeNumber : '',
    Address : 'Tbilisi',
    Email : 'Nino@Sessions.com',
    LecturerType : LecturerEnum.Invited,
    FreeTime : [new Date(2020,1,1,9,0,0), new Date(2020,1,1,12,0,0)],
    Subjects : [
        SubjectEnum.IntroductionToPsychology,
        SubjectEnum.AdvancedDataStructures,
        SubjectEnum.ArchitectureStudio,
        SubjectEnum.BiologicalChemistry,
        SubjectEnum.DarwinAndDesign,
        SubjectEnum.English,
        // SubjectEnum.FinanceTheory,
        SubjectEnum.FundamentalsOfBiology,
        SubjectEnum.Georgian,
    ],
},
{
    Id : 5 ,
    PersonalId : '5555555555555',
    FirstName : 'Khvicha',
    LastName : 'Giorgadze',
    PhoneNumber : '555675678987',
    HomeNumber : '',
    Address : 'Tbilisi',
    Email : 'Khvicha@Sessions.com',
    LecturerType : LecturerEnum.Invited,
    FreeTime : [new Date(2020,1,1,14,0,0), new Date(2020,1,1,21,0,0)],
    Subjects : [
        SubjectEnum.GameDesign,
        SubjectEnum.IntroductionToPsychology,
        SubjectEnum.AdvancedDataStructures,
        SubjectEnum.ArchitectureStudio,
        SubjectEnum.BiologicalChemistry,
        SubjectEnum.DarwinAndDesign,
        SubjectEnum.English,
    ],
}]
